
# When ready for live, with root domain:
baseURL       = "https://msirikasem.com/"

# Dev, github URL:
#baseURL       = "https://msirikasem.github.io/msirikasem.com/"

languageCode  = "en-us"
title         = "Melissa Sirikasem | Professional Design Services"
theme         = "roxo"
summarylength = 25
publishDir    = "docs"

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name          = "Home"
    url           = ""
    identifier    = "menu-home"
    weight        = 1
  [[menu.nav]]
    name          = "Work"
    url           = "portfolio"
    identifier    = "menu-work"
    weight        = 2
  [[menu.nav]]
    name          = "About"
    url           = "about"
    identifier    = "menu-about"
    weight        = 3
  [[menu.nav]]
    name          = "Contact"
    url           = "contact"
    identifier    = "menu-contact"
    weight        = 4

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Melissa Sirikasem | Professional Design Services"
  author = "Melissa Sirikasem"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Contact"
    url     = "contact"

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = ""
    heading               = "I merge fantasy and reality, bringing visions to life digitally."
    tagline               = "Hello, I'm Melissa"

  [params.portfolio]
    enable    = true
    title     = "MY PROJECTS"
    subtitle  = ""

  [params.call_to_action]
    enable              = true
    background_image    = ""
    title               = ""
    primary_button        = "résumé"
    primary_button_url    = "resume"
    secondary_button      = "say hello"
    secondary_button_url  = "contact"

  [params.footer]
    # Footer Sitemap
    [params.footer.sitemap]
      title   = "Sitemap"
      [[params.footer.sitemap.link]]
        name = "About"
        url  = "about"
      [[params.footer.sitemap.link]]
        name = "Portfolio"
        url  = "portfolio"
      [[params.footer.sitemap.link]]
        name = "Contact"
        url  = "contact"

    # Footer Social Media
    [params.footer.social]
      title   = "Social Media"
      [[params.footer.social.link]]
        name = "LinkedIn"
        url  = "https://www.linkedin.com/in/msirikasem/"

    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact"
      email   = "msirikasem@gmail.com"

